# Generated by Django 2.2.1 on 2019-07-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20190630_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='pessoa',
            new_name='client',
        ),
    ]
